DROP TABLE IF EXISTS tokens CASCADE;

CREATE TABLE tokens (
   id SERIAL PRIMARY KEY,
   username VARCHAR(255) NOT NULL UNIQUE,
   role INTEGER NOT NULL CHECK (role > 0 AND role < 3),
   token VARCHAR(500) NOT NULL UNIQUE,
   expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

